# Generated by Django 5.2.9 on 2026-01-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('customer', 'Клиент'), ('waiter', 'Официант'), ('chef', 'Повар')], default='customer', max_length=20),
        ),
    ]
